Add Test_TerraformExec_Leak to check for leaked goroutines in tf-exec
Test does a goroutine check before and after tf-exec is called. Expect this
test to fail because this issue will be resolved in next commit with a version
upgrade

Failure:

```
=== RUN   Test_TerraformExec_Leak
    /Users/lornasong/go/src/github.com/hashicorp/consul-terraform-sync/client/terraform_exec_test.go:60:
        	Error Trace:	terraform_exec_test.go:60
        	Error:      	Not equal:
        	            	expected: 2
        	            	actual  : 6
        	Test:       	Test_TerraformExec_Leak
        	Messages:   	the number of goroutines after the terraform requests should be the same as before
--- FAIL: Test_TerraformExec_Leak (1.36s)
```