Stop inspect/once when WatchDep errors
Added tests:
 - Test_ReadOnly_Run_WatchDep_errors
 - Test_ReadWrite_Once_WatchDep_errors_Terraform

Without changes, the tests fail because they timed out:

```
--- FAIL: Test_ReadOnly_Run_WatchDep_errors (5.00s)
    readonly_test.go:202: Run did not exit properly after WatcherDep errored
--- FAIL: Test_ReadWrite_Once_WatchDep_errors_Terraform (5.00s)
    readwrite_test.go:329: Once did not exit properly after WatcherDep errored
```

Note: will reuse testOnceWatchDepErrors