Convert tests over to TasksManager
Did a direct find and replace in condition_monitor_test.go and
tasks_manager_test.go for the following in order

 - TestServer => Test_TasksManager
 - TestReadWrite => Test_TasksManager
 - TestReadWrite_Run => Test_TasksManager_RunInspect
 - ReadWrite => TasksManager
 - ReadOnly => TasksManager
 - controller => tm
 - ctrl => tm
 - newTestController => newTestTasksManager

Exception: "package controller"