Fix benchmark errors finding Terraform binary
This resolves 2 errors separate issues where the benchmark tests are unable to
find the Terraform binary.

```
[ERROR] cli: error running controller: error=\"error tf-init for 'test-services-task': fork/exec /home/circleci/project/e2e/benchmarks/terraform: no such file or directory\"
```
Solution: in circleci/config.yml move terraform to e2e/benchmarks

```
[ERROR] ctrl: error initializing task: task_name=BenchmarkTasksConcurrent_t01_s50_task_000
Error Trace: tasks_concurrent_test.go:85
             tasks_concurrent_test.go:25
Error:        Received unexpected error:
              fork/exec ../../../terraform: no such file or directory
              error tf-init for 'BenchmarkTasksConcurrent_t01_s50_task_000'
```
Solution: A subset of benchmark tests have separate code to build the config.
Particularly, the terraform.path value is set differently. Update to use
os.Getwd() like other benchmark test configs