Update hcat from cts-0.4.1 to lastest on master
 - Pull in breaking change for status filtering
 - Pulls in other changes (refactor and buffer_period changes)

Makes changes for the following errors:
 - *catalogServicesRegistrationQuery does not implement dep.Dependency (missing ID method)
 - *servicesRegexQuery does not implement dep.Dependency (missing ID method)
 - undefined: hcat.FuncMapConsulV1

Make changes for failed test cases TestLoadDynamicConfig_ConsulKV:
 - Error: "template: d162a4c38127649248671cc04b2583ce:1: function "key" not defined"
 - Cause: template.Execute used to come with built-in funcs like "key" but these
 were removed: https://github.com/hashicorp/hcat/commit/a385551df88450c70cfc54e1ba2eb6221c169bf9#diff-c6ddd4d5eaa5b8cfa1478db9ae06c6261923be5add019c441bb9d4f1b1ff12b4
 - Solution: manually add back Consul and Vault functions