Update Test_TerraformExec_Leak to use tf-exec directly
Test_TerraformExec_Leak was a little flakey with GHA (see error below). Swap
from using the CTS wrapper around terraform-exec (which did other stuff like
change workspaces) and use terraform-exec directly to init and apply.

```
Error: -23T20:45:45.954Z [ERROR] client.terraformcli: unable to change workspace: workspace="" error="exit status 1"
    terraform_exec_test.go:60:
        	Error Trace:	terraform_exec_test.go:60
        	Error:      	Not equal:
        	            	expected: 22
        	            	actual  : 24
        	Test:       	Test_TerraformExec_Leak
        	Messages:   	the number of goroutines after the terraform requests should be the same as before
```