Fix flakiness in Test_ReadOnly_Run
Runs locally without issue but in CircleCi there is an error that went away
after rerun:
```
--- FAIL: Test_ReadOnly_Run (0.01s)
    --- FAIL: Test_ReadOnly_Run/one_task (0.00s)
        readonly_test.go:246: PASS:	WaitCh(string)
        readonly_test.go:246: FAIL:	Size()
            		at: [readonly_test.go:232 readonly_test.go:64]
        readonly_test.go:246: FAIL: 1 out of 2 expectation(s) were met.
            	The code you are testing needs to make 1 more call(s).
            	at: [readonly_test.go:246 readonly_test.go:64]
```